---
- name: Deploy Prometheus, Loki, and Grafana with Docker Compose
  hosts: server2
  become: yes

  vars:
    prometheus_config: /etc/prometheus/prometheus.yml
    docker_compose_file: /etc/docker-compose.yml

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Prometheus configuration directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Create directories for data storage
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var/lib/prometheus
        - /var/lib/loki
        - /var/lib/grafana

    - name: Copy Prometheus configuration file
      template:
        src: templates/prometheus.yml.j2
        dest: "{{ prometheus_config }}"

    - name: Copy Docker Compose file
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ docker_compose_file }}"

    - name: Run Docker Compose up
      shell: docker-compose -f {{ docker_compose_file }} up -d
